--- #YAML:1.0
name:                Sort-Key-Merger
version:             0.10_02
abstract:            Perl extension for merging sorted things
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Sort::Key:                     1.30_01
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
