# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sort-Key-Merger
version:      0.06
version_from: lib/Sort/Key/Merger.pm
installdirs:  site
requires:
    Sort::Key:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
